services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
